export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN = 'SIGNIN';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';

export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL';

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';


export const LOAD_ACTIVE_BIDS = 'LOAD_ACTIVE_BIDS';
export const LOAD_ACTIVE_BIDS_SUCCESS = 'LOAD_ACTIVE_BIDS_SUCCESS';
export const LOAD_ACTIVE_BIDS_FAIL = 'LOAD_ACTIVE_BIDS_FAIL';

export const LOAD_INACTIVE_BIDS = 'LOAD_INACTIVE_BIDS';
export const LOAD_INACTIVE_BIDS_SUCCESS = 'LOAD_INACTIVE_BIDS_SUCCESS';
export const LOAD_INACTIVE_BIDS_FAIL = 'LOAD_INACTIVE_BIDS_FAIL';

export const POST_NEW_BID = 'POST_NEW_BID';
export const POST_NEW_BID_SUCCESS = 'POST_NEW_BID_SUCCESS';
export const POST_NEW_BID_FAIL = 'POST_NEW_BID_FAIL';

export const GET_BID_SUCCESS = 'GET_BID_SUCCESS';
export const GET_BID_FAIL = 'GET_BID_FAIL';

export const PUT_SAVE_BID = 'PUT_SAVE_BID';
export const PUT_SAVE_BID_SUCCESS = 'PUT_SAVE_BID_SUCCESS';

export const PUT_INVITE_BID = 'PUT_INVITE_BID';
export const PUT_INVITE_BID_SUCCESS = 'PUT_INVITE_BID_SUCCESS';

export const PUT_SUBMIT_BID = 'PUT_SUBMIT_BID';
export const PUT_SUBMIT_BIDD_SUCCESS = 'PUT_SUBMIT_BID_SUCCESS';
export const PUT_SUBMIT_BID_FAIL = 'PUT_SUBMIT_BID_FAIL';
